# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Metadata
group=dev.upcraft.examplemod
mod_id=examplemod
mod_description=Template Mod.
mod_display_name=ExampleMod
sources_url=https://github.com/Up-Mods/multiloader-template
issues_url=https://github.com/Up-Mods/multiloader-template/issues
license_url=https://github.com/Up-Mods/multiloader-template/blob/HEAD/LICENSE.md
discord_url=https://mods.upcraft.dev/discord
homepage_url=https://github.com/Up-Mods/multiloader-template
#curseforge_id=0
#modrinth_id=0
